name: Trigger Playwright Automation
on:
  pull_request:
    branches: [ main, master ]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch to Playwright repo
        env:
          GITHUB_TOKEN: ${{ secrets.PLAYWRIGHT_TRIGGER_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/Parkland-Corporation-CEP/qa-automation-tests/dispatches \
            -d '{"event_type": "run-tests"}'
