name: Trigger Playwright Automation

on:
  pull_request:
    branches: [main, master]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Trigger the repository_dispatch event
      - name: Trigger Playwright Automation Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.PLAYWRIGHT_TRIGGER_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" \
            --data '{"event_type": "run-tests"}' \
            https://api.github.com/repos/Parkland-Corporation-CEP/qa-automation-tests/dispatches

      # Step 2: Wait for Playwright Workflow Completion
      - name: Wait for QA Automation Workflow
        uses: jakejarvis/wait-for-gh-action@v1
        with:
          owner: Parkland-Corporation-CEP
          repo: qa-automation-tests
          ref: main
          workflow: Playwright Tests
          token: ${{ secrets.PLAYWRIGHT_TRIGGER_TOKEN }}

      # Step 3: Download Test Artifacts
      - name: Download Playwright Test Result
        env:
          GITHUB_TOKEN: ${{ secrets.PLAYWRIGHT_TRIGGER_TOKEN }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -L \
            https://api.github.com/repos/Parkland-Corporation-CEP/qa-automation-tests/actions/artifacts \
            -o playwright-report.zip
          unzip playwright-report.zip -d playwright-results

      # Step 4: Use the Test Artifacts
      - name: Display Playwright Test Results
        run: |
          echo "Test results:"
          ls playwright-results
          cat playwright-results/index.html # Example to preview the results
